substitutions:
# Device setting  
  board: esp32-s3-devkitc-1
  name: "esp-smart-knob"
  friendly_name: "SmartKnob"
  comment: ESP Smart Knob
  type: esp-idf  
  
esphome:
  friendly_name: "${friendly_name}"
  name: "${name}"
  comment: "${comment}"
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 80000000L
    board_build.f_cpu: 240000000L
    
esp32:
  board: ${board}
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    #version: 4.4.8
    #platform_version: 5.4.0
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
      CONFIG_SPIRAM_RODATA: "y"

      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240=: "y"
      CONFIG_FREERTOS_HZ=: "1000"
      CONFIG_ESPTOOLPY_FLASHMODE_QIO=: "y"
      CONFIG_ESPTOOLPY_FLASHFREQ_120M=: "y"
      CONFIG_SPIRAM_MODE_OCT=: "y"
      CONFIG_SPIRAM_SPEED_120M=: "y"
      CONFIG_COMPILER_OPTIMIZATION_PERF=: "y"
    advanced:
      enable_idf_experimental_features: true

#psram:
  #mode: octal
  #speed: 120MHz